event_tag_data = [{"event_id": 1, "word": "coldplay"},
                   {"event_id": 1, "word": "Hyarkon"},
                   {"event_id": 1, "word": "pop"},
                   {"event_id": 2, "word": "bon"},
                   {"event_id": 2, "word": "jovi"},
                   {"event_id": 2, "word": "central"},
                   {"event_id": 3, "word": "football"},
                   {"event_id": 3, "word": "macabi"},
                   {"event_id": 3, "word": "hapoel"},
                   {"event_id": 5, "word": "batsheva"},
                   {"event_id": 5, "word": "suzzan"},
                   {"event_id": 5, "word": "dallal"},
                   {"event_id": 4, "word": "sol"},
                   {"event_id": 4, "word": "dance"},
                   {"event_id": 4, "word": "georget"}]
