ticket_tag_data = [{"ticket_id": 1, "word": "coldplay"},
                   {"ticket_id": 1, "word": "Hyarkon"},
                   {"ticket_id": 1, "word": "pop"},
                   {"ticket_id": 2, "word": "bon"},
                   {"ticket_id": 2, "word": "jovi"},
                   {"ticket_id": 2, "word": "central"},
                   {"ticket_id": 3, "word": "football"},
                   {"ticket_id": 3, "word": "macabi"},
                   {"ticket_id": 3, "word": "hapoel"},
                   {"ticket_id": 4, "word": "barcelona"},
                   {"ticket_id": 4, "word": "madrid"},
                   {"ticket_id": 4, "word": "Hyarkon"},
                   {"ticket_id": 6, "word": "batsheva"},
                   {"ticket_id": 6, "word": "suzzan"},
                   {"ticket_id": 6, "word": "dallal"}, ]
